export const CHAT_BOTTOM_STATUS_GUTTER_PX = 8;
export const CHAT_BOTTOM_SPACER_DESKTOP_PX = 32;
export const CHAT_BOTTOM_SPACER_MOBILE_PX = 40;

export const CHAT_BOTTOM_ZONE_DESKTOP_PX =
    CHAT_BOTTOM_STATUS_GUTTER_PX + CHAT_BOTTOM_SPACER_DESKTOP_PX;
export const CHAT_BOTTOM_ZONE_MOBILE_PX = CHAT_BOTTOM_SPACER_MOBILE_PX;
