import type { Session } from '@opencode-ai/sdk/v2';

// Recap + suggested follow-up generated by the server's session-assist
// watcher, stored under session.metadata.openchamber.assist. Freshness is
// encoded in forMessageID: the payload is only valid while that message is
// still the session's last assistant message.
export interface SessionAssistPayload {
  recap: string;
  suggestion: string;
  forMessageID: string;
  generatedAt: number;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === 'object' && !Array.isArray(value);

export function getSessionAssist(session: Session | null | undefined): SessionAssistPayload | null {
  const metadata = (session as { metadata?: unknown } | null | undefined)?.metadata;
  if (!isRecord(metadata)) return null;
  const namespace = metadata.openchamber;
  if (!isRecord(namespace)) return null;
  const assist = namespace.assist;
  if (!isRecord(assist)) return null;

  const recap = typeof assist.recap === 'string' ? assist.recap.trim() : '';
  const suggestion = typeof assist.suggestion === 'string' ? assist.suggestion.trim() : '';
  const forMessageID = typeof assist.forMessageID === 'string' ? assist.forMessageID : '';
  if (!forMessageID || (!recap && !suggestion)) return null;

  return {
    recap,
    suggestion,
    forMessageID,
    generatedAt: typeof assist.generatedAt === 'number' ? assist.generatedAt : 0,
  };
}

/**
 * The v2 freshness rule (OC2 spine S6, upstream cb7400923): OpenCode 2 ends
 * every turn with an idle record, so on a v2 server the newest loaded message
 * is never the answer anymore and the v1 "target is still the last message"
 * check never passes. Freshness is decided from the session record alone:
 * generated after the last idle, session not reverted. The v1 track keeps the
 * v1 rule — call sites branch on the resolved protocol handle's mode.
 */
export function getCurrentSessionAssist(session: Session | null | undefined): SessionAssistPayload | null {
  const assist = getSessionAssist(session);
  if (!assist || !session) return null;
  const reverted = Boolean((session as { revert?: { messageID?: string } | null }).revert?.messageID);
  if (reverted) return null;
  const idleAt = (session as { time?: { idle?: number } | null }).time?.idle ?? 0;
  return assist.generatedAt >= idleAt ? assist : null;
}
