import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

const DIST_DIR = join(import.meta.dirname, '..', 'packages', 'web', 'dist');
const OUT_FILE = join(import.meta.dirname, '..', 'packages', 'web', 'bin', 'embedded-assets.generated.mjs');

async function* walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

async function main() {
  const files = [];
  for await (const f of walk(DIST_DIR)) {
    files.push(f);
  }

  const entries = await Promise.all(
    files.map(async (f) => {
      const rel = relative(DIST_DIR, f);
      const buf = await readFile(f);
      const b64 = buf.toString('base64');
      return [rel, b64];
    })
  );

  const code = `// Auto-generated by scripts/embed-assets.mjs — DO NOT EDIT
export const EMBEDDED_ASSETS = new Map([
${entries.map(([k, v]) => `  [${JSON.stringify(k)}, ${JSON.stringify(v)}],`).join('\n')}
]);
`;

  await writeFile(OUT_FILE, code, 'utf8');
  const totalMb = entries.reduce((s, [k, v]) => s + v.length * 0.75 / 1e6, 0);
  console.log(`Generated ${OUT_FILE} — ${entries.length} files (${totalMb.toFixed(1)}MB base64)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
