import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

const DIST_DIR = join(import.meta.dirname, '..', 'packages', 'web', 'dist');
const OUT_FILE = join(import.meta.dirname, '..', 'packages', 'web', 'bin', 'embedded-assets.generated.mjs');
const PLUGIN_ENTRY = join(import.meta.dirname, '..', 'packages', 'plugin', 'src', 'index.ts');
const PLUGIN_OUT_FILE = join(import.meta.dirname, '..', 'packages', 'web', 'bin', 'embedded-plugin.generated.mjs');

async function* walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

async function main() {
  const files = [];
  for await (const f of walk(DIST_DIR)) {
    files.push(f);
  }

  const entries = await Promise.all(
    files.map(async (f) => {
      const rel = relative(DIST_DIR, f);
      const buf = await readFile(f);
      const b64 = buf.toString('base64');
      return [rel, b64];
    })
  );

  const pluginBuild = await Bun.build({
    entrypoints: [PLUGIN_ENTRY],
    target: 'bun',
    format: 'esm',
  });
  if (!pluginBuild.success || pluginBuild.outputs.length !== 1) {
    throw new Error(`Failed to bundle OpenChamber plugin: ${pluginBuild.logs.join('\n')}`);
  }
  const pluginBuffer = Buffer.from(await pluginBuild.outputs[0].arrayBuffer());

  const code = `// Auto-generated by scripts/embed-assets.mjs — DO NOT EDIT
export const EMBEDDED_ASSETS = new Map([
${entries.map(([k, v]) => `  [${JSON.stringify(k)}, ${JSON.stringify(v)}],`).join('\n')}
]);
`;
  const pluginCode = `// Auto-generated by scripts/embed-assets.mjs — DO NOT EDIT
export const EMBEDDED_OPENCHAMBER_PLUGIN = ${JSON.stringify(pluginBuffer.toString('base64'))};
`;

  await writeFile(OUT_FILE, code, 'utf8');
  await writeFile(PLUGIN_OUT_FILE, pluginCode, 'utf8');
  const totalMb = entries.reduce((s, [k, v]) => s + v.length * 0.75 / 1e6, 0);
  console.log(`Generated ${OUT_FILE} — ${entries.length} files (${totalMb.toFixed(1)}MB assets)`);
  console.log(`Generated ${PLUGIN_OUT_FILE} — ${(pluginBuffer.length / 1e6).toFixed(1)}MB plugin`);
}

main().catch((e) => { console.error(e); process.exit(1); });
